// <auto-generated />
namespace EF_CodeFirst_FaturaProjesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OriginalDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OriginalDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201903201722147_OriginalDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
